name: gap
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.28.1=hd590300_0
  - ca-certificates=2024.6.2=hbcca054_0
  - elfutils=0.191=h924a536_0
  - gettext=0.22.5=h59595ed_2
  - gettext-tools=0.22.5=h59595ed_2
  - glew=2.1.0=h9c3ff4c_2
  - glfw3=3.2.1=0
  - gnutls=3.7.9=hb077bed_0
  - icu=73.2=h59595ed_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libarchive=3.7.4=hfca40fe_0
  - libasprintf=0.22.5=h661eb56_2
  - libasprintf-devel=0.22.5=h661eb56_2
  - libcurl=8.8.0=hca28451_0
  - libdrm=2.4.122=h4ab18f5_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=14.1.0=h77fa898_0
  - libgettextpo=0.22.5=h59595ed_2
  - libgettextpo-devel=0.22.5=h59595ed_2
  - libglu=9.0.0=he1b5a44_1001
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.7=hd590300_0
  - libllvm18=18.1.8=hc9dba70_0
  - libmicrohttpd=1.0.1=h97afed2_0
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hd590300_0
  - libpciaccess=0.18=hd590300_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=14.1.0=hc0a3c3a_0
  - libtasn1=4.19.0=h166bdaf_0
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcb=1.16=hd590300_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.7=hc051c1a_1
  - libzlib=1.3.1=h4ab18f5_1
  - llvm-openmp=18.1.8=hf5423f3_0
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=hd590300_1001
  - mesalib=24.1.2=h3ac77ca_1
  - ncurses=6.5=h59595ed_0
  - nettle=3.9.1=h7ab15ed_0
  - openssl=3.3.1=h4ab18f5_1
  - p11-kit=0.24.1=hc5aa10d_0
  - pip=24.0=py38h06a4308_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - python=3.8.19=hd12c33a_0_cpython
  - readline=8.2=h5eee18b_0
  - setuptools=69.5.1=py38h06a4308_0
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.43.0=py38h06a4308_0
  - xorg-damageproto=1.2.1=h7f98852_1002
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-glproto=1.4.17=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libx11=1.8.9=hb711507_1
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdamage=1.1.5=h7f98852_1
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxrandr=1.5.2=h7f98852_1
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-randrproto=1.5.0=h7f98852_1001
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-util-macros=1.19.3=h7f98852_0
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xf86vidmodeproto=2.3.1=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.4.6=h5eee18b_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
    - absl-py==2.1.0
    - annotated-types==0.7.0
    - antlr4-python3-runtime==4.9.3
    - anyio==4.4.0
    - attrs==24.2.0
    - bddl==1.0.1
    - beautifulsoup4==4.12.3
    - cachetools==5.3.3
    - certifi==2024.6.2
    - cffi==1.16.0
    - changefinder==0.3
    - chardet==5.2.0
    - charset-normalizer==3.3.2
    - click==8.1.7
    - clip==1.0
    - cloudpickle==3.0.0
    - contourpy==1.1.1
    - cycler==0.12.1
    - cython==3.0.0a10
    - diffusers==0.11.1
    - distro==1.9.0
    - dm-control==1.0.10
    - dm-env==1.6
    - dm-tree==0.1.8
    - docker-pycreds==0.4.0
    - easydict==1.13
    - egl-probe==1.0.2
    - einops==0.8.0
    - etils==1.3.0
    - evdev==1.7.1
    - exceptiongroup==1.2.1
    - farama-notifications==0.0.4
    - fasteners==0.19
    - fastjsonschema==2.20.0
    - filelock==3.15.4
    - fonttools==4.53.0
    - fsspec==2024.6.0
    - ftfy==6.2.3
    - future==0.18.2
    - gdown==5.2.0
    - gitdb==4.0.11
    - gitpython==3.1.43
    - glfw==2.7.0
    - google-auth==2.30.0
    - google-auth-oauthlib==1.0.0
    - grpcio==1.64.1
    - gym==0.26.2
    - gym-notices==0.0.8
    - gymnasium==1.0.0
    - h11==0.14.0
    - h5py==3.11.0
    - hdbscan==0.8.40
    - httpcore==1.0.5
    - httpx==0.27.0
    - huggingface-hub==0.23.4
    - hydra-core==1.3.2
    - idna==3.7
    - imageio==2.34.2
    - imageio-ffmpeg==0.5.1
    - importlib-metadata==8.0.0
    - importlib-resources==6.4.0
    - iniconfig==2.0.0
    - jinja2==3.1.4
    - joblib==1.4.2
    - jsonschema==4.23.0
    - jsonschema-specifications==2023.12.1
    - jupyter-core==5.7.2
    - jupytext==1.16.4
    - kiwisolver==1.4.5
    - labmaze==1.0.6
    - llvmlite==0.41.1
    - lxml==5.2.2
    - markdown==3.6
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - matplotlib==3.7.5
    - mdit-py-plugins==0.4.2
    - mdurl==0.1.2
    - mpmath==1.3.0
    - mujoco==2.3.2
    - mujoco-py==2.1.2.14
    - nbformat==5.10.4
    - networkx==3.1
    - nose==1.3.7
    - numba==0.58.1
    - numpy==1.23.0
    - numpy-quaternion==2023.0.4
    - oauthlib==3.2.2
    - omegaconf==2.3.0
    - openai==1.7.0
    - opencv-python==4.10.0.84
    - packaging==24.1
    - pandas==2.0.3
    - patsy==1.0.1
    - pillow==10.3.0
    - pkgutil-resolve-name==1.3.10
    - platformdirs==4.2.2
    - pluggy==1.5.0
    - protobuf==3.20.0
    - psutil==6.0.0
    - pyasn1==0.6.0
    - pyasn1-modules==0.4.0
    - pycparser==2.22
    - pydantic==2.8.2
    - pydantic-core==2.20.1
    - pynput==1.7.7
    - pyopengl==3.1.7
    - pyparsing==3.1.2
    - pysocks==1.7.1
    - pytest==8.3.3
    - python-dateutil==2.9.0.post0
    - python-xlib==0.33
    - pytz==2024.2
    - pyyaml==6.0.1
    - referencing==0.35.1
    - regex==2024.5.15
    - requests==2.32.3
    - requests-oauthlib==2.0.0
    - robosuite==1.4.1
    - rpds-py==0.20.1
    - rsa==4.9
    - rtree==1.3.0
    - ruptures==1.1.9
    - sapien==2.2.2
    - scikit-learn==1.3.2
    - scipy==1.10.1
    - seaborn==0.13.2
    - sentry-sdk==2.7.0
    - setproctitle==1.3.3
    - six==1.16.0
    - smmap==5.0.1
    - sniffio==1.3.1
    - soupsieve==2.5
    - statsmodels==0.14.1
    - sympy==1.12.1
    - tabulate==0.9.0
    - tensorboard==2.14.0
    - tensorboard-data-server==0.7.2
    - tensorboardx==2.6.2.2
    - termcolor==2.4.0
    - threadpoolctl==3.5.0
    - tomli==2.0.2
    - torch==2.1.0+cu121
    - torchaudio==2.1.0+cu121
    - torchvision==0.16.0+cu121
    - tqdm==4.66.4
    - traitlets==5.14.3
    - transforms3d==0.4.2
    - trimesh==4.5.3
    - triton==2.1.0
    - typing-extensions==4.12.2
    - tzdata==2024.2
    - urllib3==2.2.2
    - wandb==0.17.3
    - wcwidth==0.2.13
    - werkzeug==3.0.3
    - zipp==3.19.2
